- fastplotlib/subplot.py
use renderer resize event to set viewports for subplots, tested and works in gridplot and simple plots
see #16 for more info
> Subplot resize event

- fastplotlib/graphics/graphics.py
Create _HistogramBin class which is just a subclass of pygfx.Mesh with `bin_center` and `frequency` attributes
non-scaled `bin_interval` and `bin_centers` are attributes of `Histogram`
> More histogram graphic stuff

- fastplotlib/graphics/__init__.py
- fastplotlib/graphics/heatmap.py
- fastplotlib/subplot.py
WIP, finishes #3 when done 
https://user-images.githubusercontent.com/9403332/197385307-fec1bb58-d478-4f32-8590-7d3aa9004069.mp4
> basic heatmap implementation with row or column selection

- fastplotlib/generate_colormaps.py
- fastplotlib/utils.py
generates colormap using matplotlib if the file isn't found
this issue seems to only appear on windows if installing directly from github
> temporary fix for #37

- fastplotlib/graphics/__init__.py
- fastplotlib/graphics/linecollection.py
addresses item on roadmap 
makes a collection of lines indexable
necessary to start events system dev
> collection of lines

- fastplotlib/widgets/line_slider.py
simple line slider, for now just vertical lines. updates using ipywidgets IntSlider
> Line slider

- fastplotlib/graphics/__init__.py
- fastplotlib/graphics/_base.py
- fastplotlib/graphics/features/_present.py
- fastplotlib/graphics/line_collection.py
- fastplotlib/layouts/_base.py
@EricThomson, this finalizes the obsolescence of old mesmerize :smile: 
https://user-images.githubusercontent.com/9403332/210024533-9b88f28c-44ba-4171-baeb-1a9b5a3b4119.mp4
> line stack works, bugfix in PresentFeature

- fastplotlib/__init__.py
- fastplotlib/widgets/image.py
- expose `ImageWidget` as top level import
- better automatic determination of slider dims when not provided
- the `ImageGraphic` added to each subplot is named `"image"`
> `ImageWidget` changes

- fastplotlib/graphics/_base.py
```
"key_down",
"key_up",
"pointer_down",
"pointer_move",
"pointer_up",
"pointer_enter",
"pointer_leave",
"click",
"double_click",
"wheel",
"close",
"resize",
```
> add all the pygfx events

- fastplotlib/graphics/histogram.py
- fastplotlib/layouts/_gridplot.py
only ones that I could find...
> changing type() to isinstance()

- requirements.txt
- requirements_rtd.txt
- setup.py
> removing unneccessary dependencies

- fastplotlib/graphics/features/_base.py
- fastplotlib/graphics/features/_colors.py
- fastplotlib/graphics/features/_data.py
> better dtype handling for GPU supported types

- fastplotlib/layouts/_gridplot.py
- fastplotlib/widgets/image.py
- fix `frame_apply`, now it can properly handle `None` or missing keys if you don't want to apply a function to a subset of the subplots
- added `grid_plot_kwargs`
- added `reset_vmin_vmax()`
> ImageWidget fix frame_apply(), add grid_plot_kwargs(), reset_vmin_vmax()

- fastplotlib/graphics/features/_data.py
I really need to figure out #150 in an elegant way
> temporary workaround for image and heatmap data buffers

- fastplotlib/widgets/image.py
> fix `ImageWidget.reset_vmin_vmax()`

- fastplotlib/layouts/_base.py
adds `PlotArea.map_screen_to_world()`
```python
plot = fpl.GridPlot((2, 3))
xs = np.linspace(0, 50, 50)
sine = np.sin(xs)
def add_point(ev):
pos = ev.x, ev.y
for subplot in plot:
world_pos = subplot.map_screen_to_world(pos)
if world_pos is None:
continue
a = np.array([world_pos.x, world_pos.y, 0], dtype=np.float32)
subplot.add_scatter(a, sizes=10, colors="w")
def auto_scale_all(ev):
for subplot in plot:
subplot.auto_scale()
plot.renderer.add_event_handler(add_point, "click")
plot.renderer.add_event_handler(auto_scale_all, "pointer_move")
plot.show()
```
https://user-images.githubusercontent.com/9403332/232277927-bb28b844-dc87-4ca1-a164-c18e583fcc0d.mp4
> map screen to world, tested and works

- fastplotlib/graphics/features/_colors.py
- fastplotlib/graphics/line_collection.py
- fastplotlib/utils/functions.py
> colors="random" for line, line collection and scatter

- fastplotlib/graphics/_base.py
- fastplotlib/graphics/line_collection.py
> graphic metadata

- fastplotlib/graphics/features/_base.py
- fastplotlib/graphics/features/_colors.py
- fastplotlib/graphics/features/_data.py
closes #101, #102 
@clewis7 can you test?
> support numpy fancy indexing for colors and data features

- fastplotlib/graphics/selectors/_base_selector.py
- fastplotlib/graphics/selectors/_linear.py
- fastplotlib/graphics/selectors/_linear_region.py
- fastplotlib/graphics/selectors/_sync.py
> fix sync bug, arrow key movements are toggleable

- fastplotlib/graphics/_base.py
- fastplotlib/layouts/_gridplot.py
- fastplotlib/plot.py
closes #107, closes #119, closes #192
> small changes

- fastplotlib/graphics/image.py
- fastplotlib/graphics/selectors/__init__.py
- fastplotlib/graphics/selectors/_base_selector.py
- fastplotlib/graphics/selectors/_linear.py
- fastplotlib/graphics/selectors/_linear_region.py
- fastplotlib/graphics/selectors/_rectangle_region.py
- fastplotlib/graphics/selectors/_sync.py
- fastplotlib/layouts/_base.py
> more selector stuff

- .readthedocs.yaml
since both fastplotlib and pygfx change every week, use pygfx from main for docs build
> Docs build fix

- docs/source/api/graphic_features.rst
- fastplotlib/graphics/features/_base.py
- fastplotlib/graphics/features/_colors.py
- fastplotlib/graphics/features/_present.py
- fastplotlib/graphics/features/_thickness.py
- fastplotlib/graphics/image.py
- fastplotlib/graphics/line.py
- fastplotlib/graphics/line_collection.py
- fastplotlib/graphics/scatter.py
- fastplotlib/graphics/selectors/_linear.py
> all feature docs

- fastplotlib/widgets/image.py
#190 
add public method to ImageWidget to change the data
> set_data()

- fastplotlib/widgets/image.py
- notebooks/image_widget.ipynb
should be fixed without pulling in that other branch, my apologies
> `ImageWidget.plot` -> `ImageWidget.gridplot`, for 1 data item, use shape (1, 1)

- fastplotlib/layouts/_base.py
- fastplotlib/layouts/_subplot.py
method allows the insertion of a graphic at a given `position` and `z_level` in `self.graphics`
will help me solve my `ImageWidget` of changing shapes in `set_data()`
> add insert_graphic method

- fastplotlib/graphics/selectors/_base_selector.py
- fastplotlib/graphics/selectors/_linear.py
- fastplotlib/graphics/selectors/_linear_region.py
- notebooks/linear_region_selector.ipynb
> changes to linear region selection feature

- fastplotlib/widgets/image.py
yay! should fix all my broadcasting errors in animal_soup after merge
> set_data() with new data being different shape without broadcasting errors

- fastplotlib/layouts/_base.py
> allowing selectors to be indexed by name

- examples/line/line.py
- examples/line/line_cmap.py
- examples/line/line_colorslice.py
- examples/line/line_dataslice.py
- examples/line/line_present_scaling.py
- examples/line_collection/line_collection.py
- examples/line_collection/line_collection_cmap_values.py
- examples/line_collection/line_collection_cmap_values_qualitative.py
- examples/line_collection/line_collection_colors.py
- examples/line_collection/line_stack.py
- examples/scatter/scatter_cmap.py
- examples/screenshots/line_cmap.png
- examples/screenshots/line_collection.png
- examples/screenshots/line_collection_cmap_values.png
- examples/screenshots/line_collection_cmap_values_qualitative.png
- examples/screenshots/line_collection_colors.png
- examples/screenshots/line_stack.png
- examples/screenshots/scatter_cmap.png
- examples/tests/test_examples.py
- examples/tests/testutils.py
- fastplotlib/graphics/features/_colors.py
- fastplotlib/graphics/line.py
- fastplotlib/graphics/line_collection.py
- fastplotlib/graphics/scatter.py
- fastplotlib/utils/functions.py
- setup.py
> more cmap handling, add cmap_values

- .github/workflows/ci.yml
- .github/workflows/screenshots.yml
> fix CI to only run when not draft PR

- examples/selector_performance.ipynb
- fastplotlib/graphics/_base.py
- fastplotlib/graphics/features/_base.py
- fastplotlib/graphics/line_collection.py
- fastplotlib/widgets/image.py
> use numpy array instead of tuple for indexing collections

- fastplotlib/widgets/image.py
@clewis7 I guess we don't have a vmin vmax test which is why we missed this? Anyways we can make a test for it after #166
> change residual occurances of image_graphics to managed_graphic

- examples/notebooks/image_widget.ipynb
- fastplotlib/widgets/image.py
> image widget debug 

- examples/notebooks/heatmap.ipynb
- fastplotlib/graphics/image.py
this slipped through on #203 
We need a test for heatmap
> fix heatmap tiling after linalg refactor

- fastplotlib/graphics/selectors/__init__.py
- fastplotlib/graphics/selectors/_polygon.py
- fastplotlib/layouts/_base.py
- fastplotlib/layouts/_plot.py
very basic for now
https://github.com/kushalkolar/fastplotlib/assets/9403332/4a61327d-eafa-4d07-ad18-5a588ed7c014
> Polygon selector which can be draw

- fastplotlib/graphics/image.py
- fastplotlib/graphics/line_collection.py
- fastplotlib/layouts/_plot.py
- fastplotlib/layouts/graphic_methods_mixin.py
all examples are in docs now, will eventually have user guide and examples rendering in docs, see #279
> removing outdated code block examples

- examples/desktop/line/line_colorslice.py
- examples/desktop/line/line_dataslice.py
- examples/desktop/line/line_present_scaling.py
- examples/desktop/scatter/scatter.py
- examples/desktop/scatter/scatter_cmap.py
- examples/desktop/scatter/scatter_colorslice.py
- examples/desktop/scatter/scatter_dataslice.py
- examples/desktop/scatter/scatter_present.py
> fix examples so they can be run locally without offscreen canvas

- examples/notebooks/linear_region_selector.ipynb
- examples/notebooks/linear_selector.ipynb
- fastplotlib/graphics/_features/_selection_features.py
- fastplotlib/graphics/selectors/_base_selector.py
- fastplotlib/graphics/selectors/_linear.py
- fastplotlib/graphics/selectors/_linear_region.py
implements #297 for int and float sliders
@minel-arinel 
Usage:
```python
ipywidget_slider = IntSlider(min=0, max=100, description="slider")
selector.add_ipywidget_handler(ipywidget_slider)
```
> auto connect a ipywidget slider to a linear selector

- examples/notebooks/simple.ipynb
- fastplotlib/layouts/_gridplot.py
- fastplotlib/layouts/_plot.py
> fix flip button

- .github/workflows/ci.yml
- .github/workflows/screenshots.yml
- fastplotlib/graphics/line.py
- fastplotlib/graphics/scatter.py
> vertex_colors -> color_mode='vertex'

- fastplotlib/layouts/_base.py
in `PlotArea.auto_scale()` when width or height of scene is `0`, or `>0.01`, set it to 1
> fix `auto_scale`

- fastplotlib/graphics/_features/_base.py
- fastplotlib/graphics/_features/_colors.py
- fastplotlib/graphics/_features/_data.py
- fastplotlib/graphics/_features/_present.py
- fastplotlib/graphics/_features/_selection_features.py
- fastplotlib/graphics/_features/_sizes.py
- fastplotlib/graphics/_features/_thickness.py
> add repr for all graphic features

- fastplotlib/layouts/_gridplot.py
this will all change after #313 but I need this now for some other stuff
> add polygon button to gridplot toolbar

- examples/qt/video.py
starts #339 
We should also make qt tests for this but that is tedious :thinking:
> add qt video example

- docs/source/api/graphic_features/CmapFeature.rst
- docs/source/api/graphic_features/HeatmapCmapFeature.rst
- docs/source/api/graphic_features/ImageCmapFeature.rst
- docs/source/api/graphic_features/PointsSizesFeature.rst
- docs/source/api/graphic_features/index.rst
- docs/source/api/graphics/HeatmapGraphic.rst
- docs/source/api/graphics/ImageGraphic.rst
- docs/source/api/graphics/LineCollection.rst
- docs/source/api/graphics/LineGraphic.rst
- docs/source/api/graphics/LineStack.rst
- docs/source/api/graphics/TextGraphic.rst
- docs/source/api/selectors/LinearRegionSelector.rst
- docs/source/api/selectors/LinearSelector.rst
- docs/source/api/selectors/PolygonSelector.rst
- docs/source/api/selectors/index.rst
- docs/source/api/widgets/ImageWidget.rst
- examples/desktop/screenshots/scatter_size.png
- fastplotlib/graphics/text.py
- fastplotlib/layouts/_subplot.py
- fastplotlib/layouts/graphic_methods_mixin.py
#305
Refactored the text graphic to use properties and some more features of `pygfx TextGeometry`
> refactor text graphic

- fastplotlib/widgets/histogram_lut.py
- fastplotlib/widgets/image.py
adds text to hlut tool
https://github.com/fastplotlib/fastplotlib/assets/9403332/efcf49d7-f27a-467c-826d-e7aa543b665e
> add text to hlut

- fastplotlib/utils/functions.py
> fix normalize_min_max

- .github/workflows/ci.yml
- docs/source/api/graphics/HeatmapGraphic.rst
- docs/source/api/layouts/gridplot.rst
- docs/source/api/layouts/plot.rst
- docs/source/api/selectors/Synchronizer.rst
- docs/source/api/widgets/ImageWidget.rst
- examples/desktop/gridplot/gridplot_non_square.py
- examples/desktop/heatmap/heatmap.py
- examples/desktop/heatmap/heatmap_cmap.py
- examples/desktop/heatmap/heatmap_data.py
- examples/desktop/heatmap/heatmap_vmin_vmax.py
- examples/desktop/screenshots/gridplot_non_square.png
- examples/desktop/screenshots/heatmap.png
- examples/desktop/screenshots/heatmap_cmap.png
- examples/desktop/screenshots/heatmap_data.png
- examples/desktop/screenshots/heatmap_vmin_vmax.png
- examples/tests/testutils.py
- fastplotlib/graphics/_features/_colors.py
- fastplotlib/graphics/image.py
- fastplotlib/layouts/_plot_area.py
- fastplotlib/widgets/image.py
> bugfixes and more tests

- .gitignore
- CONTRIBUTING.md
closes #388 
@kushalkolar, how's this read?
also, do you ever commit stuff in `diffs/`?  or is it worth adding it to git ignore?
> update contrib guide for git-lfs

- docs/source/index.rst
lots of people are searching for "axes" in the docs
> add faq to docs index

- .github/workflows/pypi-publish.yml
- MANIFEST.in
- fastplotlib/__init__.py
- fastplotlib/assets/egg.gif
- fastplotlib/assets/fastplotlib_face_logo.png
- fastplotlib/layouts/_frame/_ipywidget_toolbar.py
- fastplotlib/utils/__init__.py
- fastplotlib/utils/_gpu_info.py
Displays gpu info when imported in notebooks
> gpu info upon notebook import

- fastplotlib/layouts/_utils.py
catches up with this breaking change from pygfx@main: https://github.com/pygfx/pygfx/pull/638
> set default renderer pixel_ratio=2

- docs/source/index.rst
- docs/source/user_guide/gpu.rst
adds some basic GPU info stuff to docs
> add gpu info to docs

- fastplotlib/__init__.py
I didn't pay attention that this got removed whne #406 was merged
> fix `fastplotlib.__init__`

- examples/desktop/image/image_cmap.py
- examples/desktop/image/image_rgb.py
- examples/desktop/image/image_rgbvminvmax.py
- examples/desktop/image/image_vminvmax.py
- examples/desktop/image/image_widget.py
- fastplotlib/__init__.py
Just a small example to show the image widget on desktop.
> Image widget

- docs/source/conf.py
- docs/source/generate_api.py
- fastplotlib/layouts/graphic_methods_mixin.py
- fastplotlib/utils/generate_add_methods.py
- setup.py
Now only the examples are unblacked. I can add that too if you want, but I was not sure if certain PR's may be affected.
> A bit of black

- .github/workflows/black.yml
- .github/workflows/ci.yml
- .gitignore
- setup.py
Closes #435. 
Also changes `.gitignore`, adding VS Code config file.
> Add black to setup in optional feature set for tests

- fastplotlib/layouts/_utils.py
> revert setting pixel ratio

- .github/workflows/ci.yml
- examples/tests/test_gridplot.py
- fastplotlib/layouts/_gridplot.py
- tests/test_gridplot.py
closes #425
also adds tests the various cameras and controllers kwargs, and changing cameras and controllers after gridplot create
> gridplot controllers kwarg is back, other improvements to gp

- docs/source/api/widgets/ImageWidget.rst
- examples/notebooks/image_widget.ipynb
- examples/notebooks/image_widget_test.ipynb
- examples/notebooks/screenshots/nb-image-widget-zfish-mixed-rgb-cockatoo-frame-50.png
- examples/notebooks/screenshots/nb-image-widget-zfish-mixed-rgb-cockatoo-set-data.png
- examples/notebooks/screenshots/nb-image-widget-zfish-mixed-rgb-cockatoo-windowrgb.png
- fastplotlib/widgets/image.py
> Iw refactor

- examples/qt/embed.py
- examples/qt/imagewidget.py
- examples/qt/minimal.py
updates qt examples, we should make tests for Qt at some point but maybe after we have universal UI elements across all backends
> update qt examples

- fastplotlib/__init__.py
we actually don't need `__all__` at top level
> remove `__all__` from top level

- examples/notebooks/quickstart.ipynb
https://github.com/fastplotlib/fastplotlib/assets/9403332/fd1cb28b-caaa-4d26-b136-9d8f95b8d455
> simple scatter animation example in quickstart

- examples/notebooks/quickstart.ipynb
https://github.com/fastplotlib/fastplotlib/assets/9403332/4f59203c-8838-49f9-a464-27b1298fb5d1
> cycle colors in scatter example

- docs/source/user_guide/gpu.rst
- examples/notebooks/linear_region_selector.ipynb
- examples/tests/testutils.py
- fastplotlib/graphics/line_collection.py
- fastplotlib/legends/legend.py
- fastplotlib/utils/gui.py
- fastplotlib/widgets/histogram_lut.py
- setup.py
fix #523 
As far as our tests are concerned this is the only change we require for numpy v2 compatibility
> ndarray.ptp -> np.ptp for numpy v2

- fastplotlib/widgets/histogram_lut.py
- fastplotlib/widgets/image.py
> Figure_shape in imagewidget and related histogram widget bug fix

- docs/source/conf.py
- fastplotlib/graphics/selectors/_base_selector.py
> fix `BaseSelector._move_to_pointer`

- docs/source/api/gpu.rst
- docs/source/api/graphic_features/RectangleSelectionFeature.rst
- docs/source/api/graphic_features/index.rst
- docs/source/api/graphics/ImageGraphic.rst
- docs/source/api/graphics/LineCollection.rst
- docs/source/api/graphics/LineGraphic.rst
- docs/source/api/graphics/LineStack.rst
- docs/source/api/selectors/RectangleSelector.rst
- docs/source/api/selectors/index.rst
- docs/source/conf.py
- examples/desktop/selectors/rectangle_selector.py
- examples/desktop/selectors/rectangle_selector_zoom.py
- fastplotlib/graphics/_features/__init__.py
- fastplotlib/graphics/_features/_selection_features.py
- fastplotlib/graphics/image.py
- fastplotlib/graphics/line.py
- fastplotlib/graphics/line_collection.py
- fastplotlib/graphics/selectors/__init__.py
- fastplotlib/graphics/selectors/_base_selector.py
- fastplotlib/graphics/selectors/_rectangle.py
- fastplotlib/graphics/selectors/_rectangle_region.py
> add rectangular region selector

- examples/desktop/misc/lorenz_animation.py
Had way too much fun doing this :D 
@kushalkolar just a fun example for the gallery
https://github.com/user-attachments/assets/b37da96b-3615-402f-86cb-4036e141f7a3
> add lorenz attractor example

- fastplotlib/__init__.py
- fastplotlib/utils/__init__.py
the auto gui selection code must be the first thing that runs before we run any other WGPU code for auto-canvas detection to happen correctly
> fix auto canvas detection

- fastplotlib/graphics/image.py
- fastplotlib/graphics/selectors/_rectangle.py
always need to keep in mind rows and cols XD 
fixes #619
> fix limits when rect selector is added from image

- docs/source/conf.py
- examples/machine_learning/README.rst
- examples/machine_learning/covariance.py
https://github.com/user-attachments/assets/32f3d379-deb1-4a7d-aa04-be3be6f710cb
> add example of exploration of a covariance matrix

- fastplotlib/utils/gui.py
closes #602 
also shows tooltips :D
> display adapters in HTML table upon import in notebooks

- docs/source/api/selectors/LinearRegionSelector.rst
- docs/source/api/selectors/LinearSelector.rst
- docs/source/api/selectors/RectangleSelector.rst
- fastplotlib/graphics/selectors/_base_selector.py
- fastplotlib/graphics/selectors/_linear.py
- fastplotlib/graphics/selectors/_linear_region.py
- fastplotlib/graphics/selectors/_rectangle.py
> add vertex, edge, and fill color properties

- examples/selection_tools/fft.py
https://github.com/user-attachments/assets/970659bf-a0e4-4996-bf1a-04447018f207
> add fft example

- fastplotlib/__init__.py
- fastplotlib/widgets/image_widget/__init__.py
> raise ModuleNotFoundError if user tries to import imgui and it doesn't exist

- .github/workflows/ci.yml
- examples/notebooks/nb_test_utils.py
> add macos-latest to CI matrix

- README.md
- docs/source/user_guide/faq.rst
> Update the README

- fastplotlib/layouts/_figure.py
Adds a new method `Figure.export_numpy()`.
Removes the `FigureRecorder` because that thing is hard to test and IMO kinda out of scope and a mess. Instead once we expose the "onedemand" render mode in fastplotlib which [now exists in rendercanvs](https://github.com/pygfx/rendercanvas/issues/49) we can provide examples using `Figure.export_numpy()` to export frames as numpy arrays that can then be written to disk using the user's favorite video writer, such as opencv.
@apasarkar @FlynnOConnell 
These examples currently don't work because we don't have "ondemand" mode in fastplotlib yet, documenting here for a future PR:
```python
"""
ImageWidget export images or video
==================================
This example is meant to be run in an interactive shell. To run in a script use the …
```
> reorganized Figure export stuff

- GOVERNANCE.md
As discussed with @kushalkolar, we think the governance model has worked thus far and will continue using this model moving forward. 
I propose we continue to place a year-out deadline and revisit as needed to reflect and potentially update/propose changes to the governance model.
> Update governance 

- docs/source/user_guide/faq.rst
@clewis7 fixes old links, merge asap, thanks :D
> fit old rtd links in faq

- fastplotlib/graphics/line.py
- fastplotlib/graphics/scatter.py
- fastplotlib/layouts/_graphic_methods_mixin.py
forgot to update in #689 
@FlynnOConnell FYI
> replace weird quotes, update `GraphicMethodsMixin`

- .github/workflows/docs-deploy.yml
- docs/source/conf.py
- examples/machine_learning/kmeans.py
Simple kmeans clustering example using MNIST dataset 
https://github.com/user-attachments/assets/d36738cc-17d8-48bb-b9e6-bcf6a8db6ed4
> add kmeans clustering example

- examples/window_layouts/README.rst
- fastplotlib/layouts/_plot_area.py
- fastplotlib/utils/functions.py
- tests/test_image_graphic.py
old comment lingering from when graphics were weakrefs (before we dug into the ways ipython docs gc)
> fix comment, fix doc example readme file

- examples/scatter/spinning_spiral.py
- fastplotlib/layouts/_figure.py
- fastplotlib/layouts/_imgui_figure.py
- fastplotlib/layouts/_utils.py
- setup.py
closes #749
Not officially documented for now, to enable:
`fig.imgui_show_fps = True`
Also trying to see github actions servers can handle 1 million points for the spiral example
> Imgui stats

- fastplotlib/utils/functions.py
> add ignore_dims arg to subsample_array

- fastplotlib/ui/right_click_menus/_standard_menu.py
> add show fps and blend modes to right click menu options

- docs/source/developer_notes/layouts.rst
> fix typo in dev docs

- fastplotlib/widgets/image_widget/_widget.py
> iw.current_index is now non-reentrant

- pyproject.toml
> pin to pygfx v0.10.0 for release

- fastplotlib/widgets/image_widget/_widget.py
> fix iw.set_data
