fastplotlib/layouts.py
fastplotlib/plot.py
fastplotlib/subplot.py

`pygfx` just added a `show_object()` method for controllers so it was possible to implement methods to center the camera and controller according to the bounding box of a scene or graphic (WorldObject).
https://github.com/pygfx/pygfx/pull/326
This PR implements:
- `Subplot.center_scene()`
- `Subplot.center_graphic()`
- `Subplot._refresh_camera()`
Scene centering is also done for all subplots in a `GridPlot` when `show()` is called. Likewise for `Plot.show()`

scene and graphic centering implementation

---

fastplotlib/subplot.py

@clewis7 fixes this issue which I didn't foresee, arises if multiple graphics with name `None` are added to the same subplot:
```python
File ~/repos/fastplotlib/fastplotlib/subplot.py:105, in Subplot.add_graphic(self, graphic, center)
102     graphic_names.append(g.name)
104 if graphic.name in graphic_names:
--> 105     raise ValueError(f"graphics must have unique names, current graphic names are:\n {graphic_names}")
107 self._graphics.append(graphic)
108 self.scene.add(graphic.world_object)
ValueError: graphics must have unique names, current graphic names are:
```

fix bug where subplot will not add more than one graphic with None as name

---

fastplotlib/layouts/_subplot.py
fastplotlib/widgets/image.py

`TextGraphic` is placed in the top docked viewport of the `Subplot`, positioning is a bit wonky right now.
really useful for `mesmerize-core`, example
```python3
mcorr_outputs = [df.iloc[0].caiman.get_input_movie()]
subplot_names = ["raw"]
for i, r in df.iterrows():
if i > 4:
break
mcorr_outputs.append(r.mcorr.get_output())
subplot_names.append(f"ix: {i}")
mcorr_iw = ImageWidget(
data=mcorr_outputs, 
vmin_vmax_sliders=True,
names=subplot_names,
cmap="gnuplot2"
)
mcorr_iw.show()
```

subplots can have titles now

---

fastplotlib/graphics/_base.py
fastplotlib/graphics/features/_base.py
fastplotlib/graphics/image.py
fastplotlib/graphics/line.py
fastplotlib/graphics/line_collection.py

- bugfix for handling feature events if the event handlers are methods instead of functions
- bugfix, image has cmap and not colors for `feature_events` class attr
- `Graphic.link()` can be bidirectional using kwarg `bidirectional=True`
- Basically if `bidirectional=True`, `Graphic.link()` does `target.link()` with the same arguments. `target.link()` uses `bidirectional=False` to prevent infinite recursion.
- `_set_feature()` exits (just returns) if the `previous_data.indices` is identical to the new indices, this was also necessary to prevent infinite recurusion.
- allow 1D numpy arrays for indexing `GraphicCollection`

More interaction

---

fastplotlib/graphics/features/_data.py
fastplotlib/graphics/image.py

implements #129 
not yet tested
we eventually want to move `vmin` `vmax` to `ImageCmapFeature`, but if `ImageGraphic.cmap` is `None` when using RGB data vmin vmax won't work. Need to make `ImageCmapFeature` work even without any cmap being used.

support for RGB data for `ImageGraphic`

---

README.md

We moved it to the installation page of our docs, so it's easier to add more details without polluting the readme.

The platform requirements page of wgpu has moved

---

fastplotlib/graphics/__init__.py
fastplotlib/graphics/features/__init__.py
fastplotlib/graphics/features/_base.py
fastplotlib/graphics/features/_colors.py
fastplotlib/graphics/features/_data.py
fastplotlib/graphics/image.py
fastplotlib/layouts/_subplot.py

Performance is very fast, tested with a 10,000 x 108,000 array, uses 4GB of VRAM. All features work, data slicing and setting, cmap, vmin vmax.
https://user-images.githubusercontent.com/9403332/222890300-898b9d40-6c7a-492c-b743-86d9508a6c80.mp4
note:
- currently all Tiles that make up the heatmap are updated when the data are modified, this affects performance but we are assuming that people don't need heatmaps to update at 100Hz :joy: 
- will need to think of event handling, perhaps we can make a new feature events for `HeatmapGraphic`, and perhaps `ImageGraphic too`, called **"row-clicked"** or **"col-clicked"**, which parse the low level pygfx **"click"** event and emit row or column index with respect to the data displayed in the graphic. We probably want to have multi row or multi …

HeatmapGraphic, supports dims larger than 8192

---

fastplotlib/graphics/features/_base.py
fastplotlib/graphics/features/_colors.py
fastplotlib/graphics/features/_data.py
fastplotlib/graphics/image.py

- all feature buffers are now public
- `ImageGraphic` and `HeatmapGraphic` allow setting the input array buffer directly as the texture data buffer if `isolated_buffer=False`. The default is `True`, so by default the texture data buffer is a new array that is initialized using the shape and type of the input array, and then the isolated texture data buffer is set using the input data array values.
allows this type of behavior:

better buffer handling

---

examples/garbage_collection.ipynb
fastplotlib/graphics/_base.py
fastplotlib/graphics/features/_base.py
fastplotlib/graphics/image.py
fastplotlib/graphics/line.py
fastplotlib/graphics/line_collection.py
fastplotlib/graphics/line_slider.py
fastplotlib/graphics/scatter.py
fastplotlib/graphics/text.py
fastplotlib/layouts/_base.py
fastplotlib/layouts/_subplot.py

Follows up from #159 
This implements:
- A global `WORLD_OBJECTS` dict in `fastplotlib.graphics._base` used internally by `fastplotlib` to keep track of all pygfx `WorldObject` instances in a session. `Graphic` instances only use a weak reference proxy to access their `WorldObject` using their hex id. All references to world objects outside of this dict are via proxies.
- A global `GRAPHICS` dict in `fastplotlib.layouts._base` to keep track of all `Graphic` objects, functions similar to the global world objects dict. All references to Graphic objects outside of this dict are via proxies. The various `plot.add_<graphic>` methods only return proxies.
Adds a `PlotArea.delete_graphic()` method which is the only way that a `Graphic` should be deleted. This also frees up GPU VRAM.
GPU VRAM …

garbage collection of WorldObjects 

---

fastplotlib/widgets/image.py

changes needed in order for `set_data()` to work when a `Plot` instance underlies an `ImageWidget` but a `list()` of length 1 is passed as new data...problem will be solved when `ImageWidget` is refactored to only have underlying `GridpPlot` instead of `Union[Plot, GridPlot]`

fixes to set_data()

---

fastplotlib/layouts/_subplot.py

allows forcing a canvas with just a str kwarg:
```python
import fastplotlib as fpl
plot = fpl.Plot(canvas="glfw")
data = np.random.rand(512, 512)
image_graphic = plot.add_image(data=data, name="random-image")
plot.show()
```
@EricThomson

add canvas kwarg that takes str

---

fastplotlib/layouts/_gridplot.py
fastplotlib/layouts/_subplot.py
fastplotlib/layouts/_utils.py

- maintain_aspect behavior in `GridPlot` is such that it will use the `camera.main_aspect` value by default for each subplot if `show(matain_apsect=None)`. Otherwises uses the kwarg value
- move canvas parsing to `layouts/_utils.py`, and canvas str args now works for `GridPlot`, #233 really only worked only for `Plot`

maintain aspect handling in gridplot, better canvas renderer args handling in gridplot

---

fastplotlib/widgets/image.py

So the ipywidets `Play.interval` is supposed to be the interval between frames in ms, so `1000` should be 1 fps. But it seems to be approximate (well, poorly approximate), maybe has to do with async so the timing is way off. So just arbitrary speed from 1-1000.

add playback speed option to imagewidget toolbar

---

setup.py

- numpy < 1.23 causes issues with type annotations in the form: `-> np.ndarray[Graphic]`
- use new ipywidgets and jupyter rfb, older ones in combinations can be a mess

min version pins for numpy, jupyter-rfb, ipywidgets

---

fastplotlib/graphics/_base.py
fastplotlib/graphics/image.py
fastplotlib/graphics/line.py
fastplotlib/graphics/line_collection.py

closes #306 
@clewis7 this is going to break a bunch of things, we've used `_set_feature()` in a bunch of places like the euclidean callbacks

make set_feature, reset_feature public

---

.github/workflows/ci.yml
.github/workflows/pypi-publish.yml
.github/workflows/screenshots.yml
fastplotlib/layouts/_plot.py
setup.py

1. This adds CI to test that the examples work in an environment without jupyter and ipywidgets, to make sure that the examples work in a "minimal" env with only glfw.
2. Add python 3.12 to CI
3. remove `ipywidgets` import from `layouters/_plot.py`
4. pin `pygfx>=0.1.14`

add desktop-only CI, add py312, remove `ipywidgets` import in `plot.py`, pin `pygfx>=0.1.14`

---

fastplotlib/widgets/image.py

Usage:
```python
iw.cmap
iw.cmap = ["gray", "gnuplot2"]
iw.cmap = "viridis"
```
After #166 is done we can make it easier to set cmaps in individual subplots for image graphics, but I think this will still be useful for image widget ever after we have that.

allow getting and setting cmaps in image widget

---

fastplotlib/layouts/_base.py

allows:
```python
"graphic_name" in plot
"graphic_name" in gridplot[0, 0]
graphic_obj in plot
graphic_obj in gridplot[0, 0]
```
usecase example from mesviz, makes it easy to check if a subplot has contours or not, etc.

add `in` operator to `PlotArea` base

---

fastplotlib/graphics/line_collection.py

This snuck by, our tests aren't actually checking the `@setter`:
https://github.com/fastplotlib/fastplotlib/blob/master/examples/desktop/line_collection/line_collection_cmap_values.py
https://github.com/fastplotlib/fastplotlib/blob/master/examples/desktop/line_collection/line_collection_cmap_values_qualitative.py

fix cmap_values were not set in the `@setter`

---

fastplotlib/widgets/image.py

For some reason this check doesn't work if the ImageWidget is "spawned" within a `@interact_manual` in jupyter, this will also break it in the mesviz voila app.
Need to find a more reliable way to check if running in jupyter that also works in voila.

remove jupyter check for ImageWidget

---

fastplotlib/graphics/_base.py
fastplotlib/graphics/image.py
fastplotlib/graphics/selectors/_base_selector.py
fastplotlib/graphics/selectors/_linear.py
fastplotlib/graphics/selectors/_linear_region.py
fastplotlib/graphics/selectors/_polygon.py
fastplotlib/graphics/selectors/_sync.py
fastplotlib/layouts/_base.py

WIP
Still have some issues in the context of mesviz when switching CNMF items:
```python
Exception ignored in: <function Synchronizer.__del__ at 0x7f515504dd00>
Traceback (most recent call last):
File "/home/kushal/repos/fastplotlib/fastplotlib/graphics/selectors/_sync.py", line 85, in __del__
self.remove(s)
File "/home/kushal/repos/fastplotlib/fastplotlib/graphics/selectors/_sync.py", line 43, in remove
selector.selection.remove_event_handler(self._handle_event)
^^^^^^^^^^^^^^^^^^
ReferenceError: weakly-referenced object no longer exists
/home/kushal/repos/mesmerize-viz/mesmerize_viz/_cnmf/_viz_container.py:275: FutureWarning: You are trying to use the following experimental feature, this may change in the future without warning:
CaimanDataFrameExtensions.get_params_diffs
This feature is …
```

Fix selector garbage collection

---

examples/notebooks/image_widget.ipynb
fastplotlib/graphics/selectors/_base_selector.py
fastplotlib/graphics/selectors/_linear_region.py
fastplotlib/layouts/_base.py
fastplotlib/layouts/_subplot.py
fastplotlib/widgets/histogram_lut.py
fastplotlib/widgets/image.py

closes #166
Also moved animation and render methods from `Subplot` to `PlotBase`, because we need `DockedPlotArea` to use animation functions which is required for `LinearRegionSelector` plot hooks.
https://github.com/fastplotlib/fastplotlib/assets/9403332/c7b10c5d-dc02-48e2-9b08-b664862a4aa4
remaining todo:
- ~text to display min and max next to the lines?~ Will do in another PR since text was refactored 
For now this is not easily exposed by any imports and only used by `ImageWidget`. We can expose after it stabilizes more and if we're happy with keeping this in `fastplotlib/widgets`.

histogram lut widget

---

fastplotlib/graphics/selectors/_base_selector.py

Fix the controller getting disabled since the renderer "pointer_up" event is connected to `BaseSelector._move_end()`

fix controller getting disabled

---

fastplotlib/widgets/histogram_lut.py

this is a visual tool so we don't care much about accuracy, remove the last 1-2 bins so edges.size == hist.size
The last 2 should be zeros from the flank anyways

histogram LUT calculation fix, kinda

---

fastplotlib/graphics/_base.py
fastplotlib/graphics/_features/__init__.py
fastplotlib/graphics/_features/_deleted.py
fastplotlib/graphics/image.py
fastplotlib/graphics/line.py
fastplotlib/graphics/line_collection.py
fastplotlib/graphics/scatter.py

This makes it possible to create callbacks to do things when a `Graphic` is deleted from a `PlotArea`.
~garbage collection is actinng wonky again so I need to fix that too...~ nevermind, I think was accessing stuff users wouldn't normally access in jupyter so ipython was clinging onto it, as usual :smile: 
This also changes all `feature_events` class attributes to be a `set`.
Useage:

add `Deleted` as a graphic feature

---

.gitattributes

I missed this somehow, but github still stored the gif file using git-lfs before I put in this specification :man_shrugging:

add gif files to .gitattributes

---

setup.py

We need to wait until `nbmake` catches up, see: https://github.com/treebeardtech/nbmake/issues/119

use `pytest<8` until things catch up

---

fastplotlib/layouts/_frame/_toolbar.py
fastplotlib/layouts/_record_mixin.py

After #431 I did a review of all imports. I found 2 small interesting cases, which are addressed in this PR:
* One absolute import of a fastplotlib module.
* The optional dependency `av` can easily be lazy-imported (shaving nearly 0.1 off the import time on my machine).

Lazy import av

---

fastplotlib/graphics/_base.py
fastplotlib/graphics/_features/_colors.py
fastplotlib/graphics/_features/_data.py
fastplotlib/graphics/_features/_deleted.py
fastplotlib/graphics/_features/_present.py
fastplotlib/graphics/_features/_selection_features.py
fastplotlib/graphics/_features/_sizes.py
fastplotlib/graphics/_features/_thickness.py
fastplotlib/graphics/histogram.py
fastplotlib/graphics/line.py
fastplotlib/graphics/line_collection.py
fastplotlib/graphics/scatter.py
fastplotlib/graphics/selectors/_rectangle_region.py
fastplotlib/graphics/text.py
fastplotlib/layouts/_plot.py
fastplotlib/layouts/_subplot.py

These caught my eye in my earlier review. Simple fix that makes the code a bit simplere / easier to read, but possibly also avoids bugs.
----
Context:
```py
class Foo:    
def __init__(self):
print("init Foo")
class Bar(Foo):
def __init__(self):
super().__init__()
print("init Bar")
class Spam(Bar):
def __init__(self):
super().__init__()
print("init Spam")
Spam()
```
Produces:
```
init Foo
init Bar
init Spam
```
Replacing the `super()` in `Spam`  with `super(Spam, self).__init__()` produces the same result.
But if it is replaced with `super(Foo, self).__init__()`, it produces:
```
init Foo
init Spam
```

Use simpler form of super() where possible

---

.github/workflows/ci.yml
examples/notebooks/nb_test_utils.py

closes #438
this prevents exceptions from being raised in the example notebooks which have testing cells. They are marked as "for testing, ignore" but with this PR the functions just return immediately anyways if the user has run them. The test functions now require the env var `FASTPLOTLIB_NB_TESTS="1"` to run.

env var required for nb test funcs to run

---

examples/notebooks/test_gc.ipynb
fastplotlib/graphics/_base.py
fastplotlib/graphics/line.py
fastplotlib/graphics/line_collection.py
fastplotlib/graphics/selectors/_base_selector.py
fastplotlib/graphics/selectors/_linear.py
fastplotlib/graphics/selectors/_linear_region.py
fastplotlib/graphics/selectors/_polygon.py
fastplotlib/layouts/_plot_area.py
fastplotlib/legends/legend.py
fastplotlib/widgets/histogram_lut.py
fastplotlib/widgets/image.py

closes #463
Adds new `References` object for which there is a single global instance for one instance of Python.
This helps segregate `Graphic`, `Selector`, `Legend` and any other objects we might want to have in the future. 
start using prefix `_fpl_*` for any attributes/methods that are for fpl internal use only, to distinguish them from actual private attributes
Moved selector `_fpl_cleanup` to `Graphic._fpl_cleanup`
Need to add tests for:

add `References` object to `PlotArea`, other cleanup, better garbage collection

---

docs/source/api/gpu.rst
docs/source/conf.py
docs/source/index.rst
docs/source/user_guide/gpu.rst
fastplotlib/__init__.py
fastplotlib/utils/__init__.py
fastplotlib/utils/gpu.py

basically wrapper for https://github.com/pygfx/pygfx/pull/709 and https://github.com/pygfx/wgpu-py/pull/481
Adds a `fastplotlib.utils.gpu` module, and exposes `enumerate_adapters`, `select_adapter`, and `print_wgpu_report` at top level.
Example:
```python
import fastplotlib as fpl
fpl.select_adapter(fpl.enumerate_adapters()[2])
```
Also added corresponding info to docs: https://fastplotlib--491.org.readthedocs.build/en/491/user_guide/gpu.html#gpu-info

Select gpu

---

fastplotlib/graphics/_features/_base.py

this always casts data for positions graphics to `float32`, and it tries to create a numpy array from other array types, shoulud work with jax arrays according to https://github.com/fastplotlib/fastplotlib/issues/483

always cast to float32, try to convert other array types too

---

fastplotlib/graphics/image.py

set `cmap` feature for RGB images to `None` and provide more useful feedback is user try to set or read property

disable cmap property for RGB images

---

tests/test_colors_buffer_manager.py
tests/test_positions_data_buffer_manager.py
tests/test_positions_graphics.py
tests/test_sizes_buffer_manager.py
tests/utils.py

after https://github.com/pygfx/pygfx/pull/795 `Buffer._gfx_pending_uploads` no longer exists. There are new methods `Buffer.update_full()` and `Buffer.update_indices()` which we can make use of instead of us having to check these ourselves.
One purpose of our test was to make sure that indices chosen to be uploaded correctly mapped to a range and it seems like we don't have to worry about this anymore, thanks @almarklein ! :smile: 
We should change our `BufferManagers` to make use of the new buffer upload options! :D

catchup with pygfx, remove checks for pending uploads from tests

---

fastplotlib/graphics/_axes.py

closes #561 
WIP, seems to be ok in 2D, something wonky in 3D. Those blue axes should be pointing out towards the red points. And one ruler is completely MIA
using [`pylinalg.quat_from_vecs`](https://pylinalg.readthedocs.io/en/latest/reference.html#pylinalg.quat_from_vecs) to create the quaternion to rotate the axes world object.

change basis of axes

---

fastplotlib/graphics/_features/_selection_features.py
fastplotlib/graphics/selectors/_base_selector.py
fastplotlib/graphics/selectors/_rectangle.py

followup from #592
closes #468
This fixes it for `LinearRegionSelector` too. To make it work with `RectangleRegionSelector` we need to take the bbox `selection` and get the center point, and later when we properly implement a `PolygonSelector` we can just take the mean of all vertices but we can do these later.

Fix move to pointer for selectors again

---

fastplotlib/layouts/_plot_area.py

sometimes a `NameError` is raised from the `get_ipython()` within `PlotArea.delete_graphic()`. I don't really understand it, it's bizarre especially since the garbage collection test nb works. This fixes it, let's see if we get any further issues down the line?

do get_ipython() only once in import

---

.github/workflows/ci.yml
.github/workflows/docs-deploy.yml
.github/workflows/pypi-publish.yml
.github/workflows/screenshots.yml

- `libegl1-mesa` does not exist in Ubuntu 24.04 which is [now used by github actions servers](https://github.com/actions/runner-images/issues/10636), will see if `libegl1-mesa-dev` which does exist is a substitute. @almarklein also relevant for pygfx, wgpu . See https://github.com/fastplotlib/fastplotlib/actions/runs/11323476618/job/31486223347#step:5:12
- update all our actions verisons

update github workflows

---

docs/source/api/selectors/LinearRegionSelector.rst
docs/source/api/selectors/LinearSelector.rst
fastplotlib/graphics/selectors/_linear.py
fastplotlib/graphics/selectors/_linear_region.py

since we've not switched to imgui we shouldn't have any GUI specific code in the core library, this really cleans up the selectors :smile:

remove ipywidget code from selectors and cleanup docstrings

---

docs/source/user_guide/guide.rst
fastplotlib/graphics/_base.py

Better organization of docs for events in user guide. copied a bunch of stuff from jupyter_rfb docs too so they're all in one place, easier for users

better event docs, better docstring too

---

fastplotlib/layouts/_plot_area.py

closes #582 
also cleans up the docstrings for zoom stuff in plot area

PlotArea.center_graphic() default zoom 1.35 -> 1.0

---

.github/workflows/ci.yml
.github/workflows/docs-deploy.yml
.github/workflows/pypi-publish.yml
.github/workflows/screenshots.yml

- just use `with: lfs: true` with `actions/checkout`, remove explicit apt install of `git-lfs`
- use release version of pypi publish action
- ~add python3.13~ I think we need to wait for the next built wheels of `imgui-bundle` to release, I wonder if it's to do with `scikit_build_core` since that's what it uses? Anyways python 3.13 is brand new so we can wait a few months.

cleanup CI

---

fastplotlib/graphics/_features/_image.py
fastplotlib/graphics/image.py
fastplotlib/widgets/image_widget/_widget.py

changes all the incorrect `[x, y]` shape comments to `[rows, cols]`

update comments for image data shapes

---

setup.py

Changes in the latest pyav have been blocking things: https://github.com/imageio/imageio/issues/1111
Let's switch to using ffmpeg instead, it's sufficient for our use case which is examples and docs. `imageio-ffmpeg` ships the binaries with the wheels for all OSses: https://github.com/imageio/imageio-ffmpeg?tab=readme-ov-file#installation

use imageio[ffmpeg] instead of pyav

---

.github/workflows/ci.yml
docs/source/conf.py
docs/source/user_guide/gpu.rst
examples/tests/test_examples.py
fastplotlib/graphics/_features/_image.py
tests/conftest.py

Hi,
when running different examples involving images, the following exception is raised:
```python
Traceback (most recent call last):
File "***\fastplotlib\examples\gridplot\gridplot_non_square.py", line 20, in <module>
figure[0, 0].add_image(data=im)
File "***\fastplotlib\fastplotlib\layouts\_graphic_methods_mixin.py", line 75, in add_image
return self._create_graphic(
^^^^^^^^^^^^^^^^^^^^^
File "***\fastplotlib\fastplotlib\layouts\_graphic_methods_mixin.py", line 24, in _create_graphic
graphic = graphic_class(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "***\fastplotlib\fastplotlib\graphics\image.py", line 126, in __init__
self._data = TextureArray(data, isolated_buffer=isolated_buffer)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File …
```

fix typo in the requested limit name of the wgpu device

---

fastplotlib/__init__.py
fastplotlib/utils/gui.py

- fix deprecated wgpu calls
- show a warning instead of raising an exception upon import if no wgpu adapters are found. I think it's probably not the best behavior to raise exception on import for something like this, a warning is more appropriate

small wgpu changes

---

.github/workflows/ci.yml
.github/workflows/pypi-publish.yml
.github/workflows/screenshots.yml

drop python3.10 from CI and add python3.13, mainly since [imgui-bundle now only provides wheels for python3.11-3.13](https://pypi.org/project/imgui-bundle/1.6.2/#files) in the latest release. It has to build imgui from source on python3.10 which slows down that github action job. Python 3.10 will be dropped from NEP29 in a few months anyways, we can continue unofficially supporting 3.10 meanwhile. 
also updates python versions for publish and deploy docs actions

update python versions for CI 

---

.github/workflows/ci.yml
.github/workflows/screenshots.yml

Some small cleanup and organization. Previously it would test the components (i.e. `pytest tests/`) and test examples in the same step, now separated into individual steps. Makes no difference but it makes the github actions logs easier to read and go through when things break.

Update ci step

---

.github/workflows/ci.yml

closes #702 
see this comment https://github.com/fastplotlib/fastplotlib/pull/706#issuecomment-2613724223
~Instead of adding it to the matrix I just made a new identical job so we can use the branch protection rules instead of the more complicated check and message system linked in that issue~
~Will see if this works, I've set "Test Linux" (which uses `pygfx@main`) as a required status check that must pass for a PR to be merged and I wonder if that will cover the entire matrix for that job. "Test Linux pygfx release" is however not required to pass.~

add job that uses release version of pygfx

---

fastplotlib/ui/_base.py
fastplotlib/ui/right_click_menus/_colormap_picker.py
fastplotlib/ui/right_click_menus/_standard_menu.py

fixes #694 
The kwargs for the imgui popup menu for right clicks got more strict in the v1.6.0 release. Was annoying to troubleshoot since I was first getting errors stating that the previous imgui frame had not been ended and to call `imgui.end_frame()`. So then I added an extra `imgui.end_frame()` within the right click menu and it produced the actual error which was that imgui wasn't happy with the types of the kwargs :man_shrugging: 
So before we had things like this for example:
```python
imgui.menu_item("item name", None, val > 0)
menu_item(str, str, bool)
```
args are: (item name, keyboard shortcut, selected)
So before it worked if we gave `None` for the second arg which is keyboard shortcut, now it has to explicitly be `""`. And it's not taking expressions that results in a `bool` …

Fix imgui popup menus

---

.github/workflows/ci-pygfx-release.yml
.github/workflows/ci.yml
CONTRIBUTING.md

Until pygfx becomes more stable we will have 2 workflows. One that uses `pygfx@main` another that uses the latest pygfx from pypi. Slight maintenance burden but temporary.

separate CI workflow that uses release version of pygfx

---

fastplotlib/utils/functions.py

Addresses issue #711, verified that .size is no longer a "required" property for lazy arrays used in ImageWidget.

removes size attribute use for histogram component of imagewidget

---

.github/workflows/ci-pygfx-release.yml
.github/workflows/ci.yml
.github/workflows/screenshots.yml

this changed when `wgpu-py` moved the gui stuff to `rendercanvas`, the old env var was there for backwards compatibility
@clewis7 gtg

Update `WGPU_FORCE_OFFSCREEN` to `RENDERCANVAS_FORCE_OFFSCREEN`

---

examples/selection_tools/unit_circle.py
fastplotlib/graphics/_features/_base.py
fastplotlib/graphics/_features/_common.py
fastplotlib/graphics/_features/_image.py
fastplotlib/graphics/_features/_positions_graphics.py
fastplotlib/graphics/_features/_selection_features.py
fastplotlib/graphics/_features/_text.py

This simple decorator applied on all the `GraphicFeature.set_value()` methods should allow us to create complex event graphs with cycles. Users don't have to think about managing bidirectional events :smile: 
related #741 
Example:
```python
import fastplotlib as fpl
import numpy as np
fig = fpl.Figure((3, 1))
sels = list()
for subplot in fig:
lg = subplot.add_line(np.sin(np.linspace(0, np.pi * 10, 100)))
sel = lg.add_linear_selector()
sels.append(sel)
def set_selection(ev):
for sel in sels:
sel.selection = ev.info["value"]
for sel in sels:
sel.add_event_handler(set_selection, "selection")
fig.show(maintain_aspect=False)
```
Need to test with more graphics and also test when exceptions are raised in `GraphicFeature.set_value()`
@apasarkar @FlynnOConnell you guys will love this!

implemenet `@block_reentrance` decorator

---

fastplotlib/_version.py

Using the same module as pygfx and wgpu, which includes more detailed version info when you're inside a git repo.

Use _version.py that includes details using git

---

fastplotlib/graphics/selectors/_base_selector.py

Ref #781
I noticed that the color of the selector was flickering during motion, as the mouse enters and exits the object. This PR freezes the color while `._moving`, keeping track of color changes in a dict, and then applying that dict when the moving is done.
Notice how the corner vertex becomes highlighted as the mouse is released after dragging the edge:
https://github.com/user-attachments/assets/5f5db53c-cccf-43f5-8859-f1dc1589f8cc

Improve hover color behavior for selectors

---

examples/selection_tools/linear_region_line_collection.py
examples/selection_tools/linear_region_selector.py
examples/selection_tools/linear_region_selectors_match_offsets.py
fastplotlib/graphics/selectors/_base_selector.py
fastplotlib/graphics/selectors/_linear.py
fastplotlib/graphics/selectors/_linear_region.py
fastplotlib/graphics/selectors/_polygon.py
fastplotlib/graphics/selectors/_rectangle.py
fastplotlib/layouts/_plot_area.py

Ref #781
Refactor to move the selectors based on their original value, instead of using incremental deltas. This makes it much easier to implement natural behavior when the movement is clipped by the limits.
One question: What's up with the `PolygonSelector`, I see no example of it, and it also does not implement `_move_graphic`.

Refactor selector drag behavior

---

fastplotlib/utils/functions.py

Some of my datasets are overflowing during histogram calculation. 
```python
raw_scan.shape
Out[1]: (5632, 14, 448, 448)
np.prod(raw_scan.shape)
Out[2]: -1354760192
np.prod(raw_scan.shape, dtype=np.int64)
Out[3]: 15825108992
```
Also, `ignore_dims` won't work due to tuple item assignment. Changed that to a list

coerce dtype=np.int64 for np.prod calls in subsample

---

examples/controllers/specify_integers.py
examples/gridplot/README.rst
examples/gridplot/gridplot.py
examples/gridplot/gridplot_non_square.py
examples/gridplot/gridplot_viewports_check.py
examples/gridplot/multigraphic_gridplot.py
examples/misc/multiplot_animation.py
examples/notebooks/quickstart.ipynb
examples/scatter/scatter_size.py
fastplotlib/graphics/_positions_base.py
fastplotlib/graphics/image.py
fastplotlib/graphics/line.py
fastplotlib/graphics/scatter.py
fastplotlib/graphics/selectors/_rectangle.py
fastplotlib/graphics/text.py
fastplotlib/layouts/_figure.py
fastplotlib/layouts/_graphic_methods_mixin.py
fastplotlib/utils/functions.py
fastplotlib/widgets/image_widget/_widget.py
scripts/generate_add_graphic_methods.py
tests/test_figure.py

Renamed lots of instances where gridplot was still lingering to Figure. There is no such thing as "grid plot" anymore so changed those descriptions to "grid layout".
Some other docstring cleanup, reword some things to be better. Some better error messages in `Figure.__init__()`
removed "padding" kwarg for `add_linear_selector()` methods since it's no longer required since we have inf lines :smile: 
also fixes #818 
@clewis7 ready for review

docstring and docs cleanup, other misc small things

---

fastplotlib/_version.py
pyproject.toml

I think https://github.com/pygfx/wgpu-py/issues/723 will take a while to resolve and then wait for a wgpu release before we can release fpl v0.6.0. Also once we merge #838 into main then we have to wait for the next release of pygfx before we can release fpl v0.6.0. So let's see if we can do a bugfix release for v0.5 right now to prevent users running into imgui font errors

Imgui pin to attempt bugfix release

---

fastplotlib/layouts/_figure.py

closes #733 
Added the kwarg argument to `show()` so that the axes are still created and could be flipped to visible at user's discretion

add kwarg for axes visibility
